version: '3'

services:
  mongo-api:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - mongo
    networks:
      - back

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    # volumes:
    #   - ./data:/data/db        
    networks:
      - back

networks:
  back: